### ISSUE TITLE
Tem algum exemplo prático

### ISSUE THREAD

**Issue by fabiomattes2016** [guilhermearaujo/boleto.js#11]
Teria algum exemplo prático para pegar as informações de um boleto e joga-las em caixas de texto html?

**Comment by guilhermearaujo** [comment]
Você pode usar os métodos `number()` ou `prettyNumber()` e inserir em algum elemento HTML.
```javascript
var boleto = Boleto('...')
$('your_selector').html(boleto.prettyNumber())
```
