### ISSUE TITLE
Formado do código de barras Santander

### ISSUE THREAD

**Issue by mauriciogofas** [guilhermearaujo/boleto.js#12]
Olá @guilhermearaujo, seu script, está impressionante.

Tenho uma dúvida mas não é exatamente um _issue_:

O Santander retorna duas sequências numéricas ao consumir o webservice de registro de títulos, uma num parâmetro chamado `cdBarra` e outra num parâmetro chamado `linDig` (código de barras e linha digitável).

Exemplo de _linDig_ :    `03399897259400000000300086601010674080000028998`
Exemplo de _cdBarra_ : `03396740800000289989897294000000000008660101`
  
O parâmetro linDig é renderizado e exibe o código de barras perfeitamente, inclusive os leitores ópticos de aplicativos dos bancos reconhecem todas as informações normalmente. Mas segundo o banco, o parâmetro correto para renderizar a imagem do código de barras é o `cdBarra`, porém, ao usar essa sequência numérica o boleto.js retorna o erro `Invalid bank slip number`.

Minha dúvida é: qual das duas sequências numéricas eu realmente devo usar para imprimir o código de barras dos boletos?

Gratidão por compartilhar o código e tudo mais,
[]!

**Comment by guilhermearaujo** [comment]
@mauriciogofas a numeração da `linha digitável` é uma permutação de trechos do `código de barras`, acrescido de alguns dígitos verificadores (para evitar erros humanos na hora de inserir os dados).

O valor que o construtor `Boleto` espera é a `linha digitável`. A biblioteca converte esse número no valor que é usado para gerar o código de barras, e depois gera o SVG.

Ex:
```javascript
var boleto = new Boleto('03399897259400000000300086601010674080000028998')
boleto.number()  // 03399897259400000000300086601010674080000028998 == linDig
boleto.barcode() // 03396740800000289989897294000000000008660101 == cdBara
```

**Comment by mauriciogofas** [comment]
Perfeito, obrigado!
