### ISSUE TITLE
Essa lib usa o padrão definido pela Febraban? Intervalado 2 de 5

### ISSUE THREAD

**Issue by felipebonezi** [guilhermearaujo/boleto.js#68]
Olá, boa tarde.

Gostaria de saber se o padrão da renderização do código de barras é o definido pelo Febraban: `Intervalado 2 de 5`. Sabem me dizer? Notei que não existe essa informação no README.

https://cmsarquivos.febraban.org.br/Arquivos/documentos/PDF/Layout%20-%20C%C3%B3digo%20de%20Barras%20ATUALIZADO.pdf

**Comment by guilhermearaujo** [comment]
Sim, é esse mesmo o encoding. No código está referenciado como ITF (Interleaved 2 of 5)
